cloudplayer/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.views.generic import TemplateView
from . import views

urlpatterns = patterns('cloudplayer.views',
    # Examples:
    # url(r'^$', 'cloudplayer.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^$', TemplateView.as_view(template_name='cloudplayer/index.html'), name='index'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^m/', include('music.urls', namespace='music')),
    url(r'^api/', include('music.api_urls', namespace='api')),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
)

music/urls.py
from django.conf.urls import patterns, url
from . import views
from . import api

urlpatterns = patterns('music.views',
    url(r'^$', views.TrackListView.as_view(), name='index'),
    
    url(r'^play/(?P<pk>\d+)/$', views.PlayView.as_view(), name='play'),
    
    url(r'^upload/$', views.UploadView.as_view(), name='upload'),
    url(r'^upload/success/$', views.UploadedView.as_view(), name='uploaded'),
    
    url(r'^playlists/create/$', views.PlaylistCreateView.as_view(), name='playlist-create'),
    url(r'^playlists/$', views.PlaylistListView.as_view(), name='playlists-list'),
    url(r'^playlists/(?P<pk>\d+)/$', views.PlaylistDetailView.as_view(), name='playlist-detail'),
    
    url(r'^albums/$', views.AlbumListView.as_view(), name='albums-list'),
    url(r'^albums/(?P<pk>\d+)/$', views.AlbumDetailView.as_view(), name='album-detail'),
    
    url(r'^artists/$', views.ArtistListView.as_view(), name='artists-list'),
    url(r'^artists/(?P<pk>\d+)/$', views.ArtistDetailView.as_view(), name='artist-detail'),
    
    url(r'^genres/$', views.GenreListView.as_view(), name='genres-list'),
    url(r'^genres/(?P<pk>\d+)/$', views.GenreDetailView.as_view(), name='genre-detail'),
    
    #url(),
    #url(),
    #url(),
)

cloudplayer/models.py
from django.db import models
from django.utils.timezone import now
from django.conf import settings
from os import path
from base64 import b32encode
from sendfile import sendfile
import uuid, os
import hashlib
from mutagen.id3 import ID3
from copy import deepcopy

def get_unique_file_name(filename):
    return b32encode(uuid.uuid4().bytes).strip('=').lower() + '.' + filename.split('.')[-1]

def file_location(instance, filename):
    filename = get_unique_file_name(filename)
    return filename

def write_temp_file(f):
    fn = path.join(settings.TEMP_FILE_ROOT, get_unique_file_name(f.name))
    with open(fn, 'wb+') as destination:
        for chunk in f.chunks():
            destination.write(chunk)
    return fn

class Tags(object):
    def __init__(self, fn):
        try:
            self._audioinfo = ID3(fn)
        except Exception as e:
            self._audioinfo = {}

        self._load_tags()
        
    def _load_tags(self):
        self._tags = {}
        for key, value in self._audioinfo.iteritems():
            self._tags[key] = value

    def delete(self):
        if self._audioinfo:
            self._audioinfo.delete()

    @property
    def track(self):
        return self._get_attr('TRCK')

    @property
    def title(self):
        return self._get_attr('TIT2')

    @property
    def artist(self):
        return self._get_attr('TPE1')

    @property
    def album(self):
        return self._get_attr('TALB')

    @property
    def image(self):
        apic = self._tags.get('APIC:')
        if apic:
            return apic.data
        return None

    def _get_attr(self, name):
        attr = self._tags.get(name)
        if attr:
            return self._tags.get(name).text[0]
        return None
    

class FileManager(models.Manager):
    def create(self, **kwargs):
        instance = File(**kwargs)
        
        fn = write_temp_file(instance.file)
        
        tags = Tags(fn)
        tags.delete()

        with open(fn, 'r') as temp_file:
            sha = hashlib.sha256(temp_file.read()).hexdigest()
            instance.hash = sha
        try:
            instance.save()
        except Exception as e:
            instance = self.get(hash=sha)

        #os.remove(fn)
        return instance, tags


class File(models.Model):
    hash = models.CharField(max_length=64, unique=True)
    file = models.FileField(upload_to=file_location)
    play_count = models.BigIntegerField(default=0)
    date_created = models.DateTimeField(auto_now_add=True)
    date_modified = models.DateTimeField(auto_now=True)
    
    objects = FileManager()
    
    def send(self, request):
        self.play_count+=1
        self.save()
        return sendfile(request, self.get_path())
    
    def get_path(self):
        return '{}/{}'.format(
            settings.MEDIA_ROOT,
            self.file.url
        )

cloudplayer/forms.py
from django import forms
from multiupload.fields import MultiFileField

class FileUploadForm(forms.Form):
    files = MultiFileField(max_num=100, min_num=1, max_file_size=1024*1024*5)

cloudplayer/views.py
from . import forms, models
from django.views.generic import FormView
from django.contrib import messages

cloudplayer/templates/cloudplayer/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div id="sidebar">
	<div id="menu-region">
		
	</div>
	<div class='player' id="player-region">
		
	</div>
</div>
<div id="main-content">
	<div id="main-region">
		
	</div>
	<div class="bottom-strip">
		
		<div class="file-dropzone" id="dropzone">
			<h1 class="text-center">Drop files here</h1>
			<form action="{% url 'music:upload' %}">
				{% csrf_token %}
			</form>
		</div>
	</div>
</div>

{% endblock content %}

{% block templates %}

<script type="text/template" id="track-list-item-tmpl">{% include 'cloudplayer/_templates/track-list-item.html' %}</script>
<script type="text/template" id="track-list-tmpl">{% include 'cloudplayer/_templates/track-list.html' %}</script>

<script type="text/template" id="album-list-item-tmpl">{% include 'cloudplayer/_templates/album-list-item.html' %}</script>
<script type="text/template" id="album-list-tmpl">{% include 'cloudplayer/_templates/album-list.html' %}</script>

<script type="text/template" id="playlist-list-item-tmpl">{% include 'cloudplayer/_templates/playlist-list-item.html' %}</script>
<script type="text/template" id="playlist-list-tmpl">{% include 'cloudplayer/_templates/playlist-list.html' %}</script>

<script type="text/template" id="menu-list-item-tmpl">{% include 'cloudplayer/_templates/menu-list-item.html' %}</script>
<script type="text/template" id="menu-list-tmpl">{% include 'cloudplayer/_templates/menu-list.html' %}</script>

<script type="text/template" id="player-tmpl">{% include 'cloudplayer/_templates/player.html' %}</script>

{% endblock templates %}

{% block scripts %}
<script type="text/javascript" src="{% static 'cloudplayer/js/app.js' %}"></script>

<script type="text/javascript" src="{% static 'cloudplayer/js/apps/player/app.js' %}"></script>
<script type="text/javascript" src="{% static 'cloudplayer/js/apps/player/views.js' %}"></script>
<script type="text/javascript" src="{% static 'cloudplayer/js/apps/player/controller.js' %}"></script>

<script type="text/javascript" src="{% static 'cloudplayer/js/apps/tracks/app.js' %}"></script>
<script type="text/javascript" src="{% static 'cloudplayer/js/apps/tracks/list/views.js' %}"></script>
<script type="text/javascript" src="{% static 'cloudplayer/js/apps/tracks/list/controller.js' %}"></script>

<script type="text/javascript" src="{% static 'cloudplayer/js/apps/albums/app.js' %}"></script>
<script type="text/javascript" src="{% static 'cloudplayer/js/apps/albums/list/views.js' %}"></script>
<script type="text/javascript" src="{% static 'cloudplayer/js/apps/albums/list/controller.js' %}"></script>

<script type="text/javascript" src="{% static 'cloudplayer/js/apps/playlists/app.js' %}"></script>
<script type="text/javascript" src="{% static 'cloudplayer/js/apps/playlists/list/views.js' %}"></script>
<script type="text/javascript" src="{% static 'cloudplayer/js/apps/playlists/list/controller.js' %}"></script>

<script type="text/javascript" src="{% static 'cloudplayer/js/apps/menu/app.js' %}"></script>
<script type="text/javascript" src="{% static 'cloudplayer/js/apps/menu/list/views.js' %}"></script>
<script type="text/javascript" src="{% static 'cloudplayer/js/apps/menu/list/controller.js' %}"></script>

<script type="text/javascript" src="{% static 'cloudplayer/js/entities/track.js' %}"></script>
<script type="text/javascript" src="{% static 'cloudplayer/js/entities/album.js' %}"></script>
<script type="text/javascript" src="{% static 'cloudplayer/js/entities/playlist.js' %}"></script>
<script type="text/javascript" src="{% static 'cloudplayer/js/entities/menu.js' %}"></script>
<script type="text/javascript">
	CloudPlayer.start();
</script>
{% endblock scripts %}